development:
  adapter: sqlite3
  database: development.sqlite
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: heroku
  pool: 5
  timeout: 5000
