# Create 20 Users
User.create(email: "lkadsfhkj@aol.com", username: "JJWat66")
User.create(email: "lkadsfhkj@aol.com", username: "Pohf77")
User.create(email: "lkadsfhkj@aol.com", username: "VinceStaples9")
User.create(email: "lkadsfhkj@aol.com", username: "EarlSweat6")
User.create(email: "lkadsfhkj@aol.com", username: "TylerC")
User.create(email: "lkadsfhkj@aol.com", username: "Proper669")
User.create(email: "lkadsfhkj@aol.com", username: "EverythingPoop")
User.create(email: "lkadsfhkj@aol.com", username: "LoveMonkey69")
User.create(email: "lkadsfhkj@aol.com", username: "RobWillRI")
User.create(email: "lkadsfhkj@aol.com", username: "ZombieCakeFart")
User.create(email: "lkadsfhkj@aol.com", username: "Cosmosomoc")
User.create(email: "lkadsfhkj@aol.com", username: "MathStudent6")
User.create(email: "lkadsfhkj@aol.com", username: "TruthLiesBrown")
User.create(email: "lkadsfhkj@aol.com", username: "TwerkPurposeForJes")
User.create(email: "lkadsfhkj@aol.com", username: "BendOverMAngo")
User.create(email: "lkadsfhkj@aol.com", username: "FolgersSm3lls")
User.create(email: "lkadsfhkj@aol.com", username: "GiraffesThinkAlot")
User.create(email: "lkadsfhkj@aol.com", username: "PooplickUSA")
User.create(email: "lkadsfhkj@aol.com", username: "CamelTrain")
User.create(email: "lkadsfhkj@aol.com", username: "BabyStink")
User.create(email: "lkadsfhkj@aol.com", username: "GradeWeaopern")

# Ceeate 5 Festivals
fest1 = Festival.create(name: "Coachella", location: "Indio, CA", date: 2017-04-04, created_by_user_id: 2)
fest2 = Festival.create(name: "Outside Lands", location: "San Francisco, CA", date: 2018-03-01, created_by_user_id: 5)
fest3 = Festival.create(name: "Electric Daisy Carnival", location: "Las Vegas, NV", date: 2017-06-20, created_by_user_id: 9)
fest4 = Festival.create(name: "Electric Forest", location: "Ann Arbor, MI", date: 2018-02-23, created_by_user_id: 10)
fest5 = Festival.create(name: "Ultra Music Festival", location: "Miami, FL", date: 2018-05-10, created_by_user_id: 15)

# Create 10 Artists
fest1.artists.create(name: "Flume", genre: "Future Bass")
fest2.artists.create(name: "Porter Robinson", genre: "Future Bass")
fest3.artists.create(name: "Beck", genre: "Rock")
fest4.artists.create(name: "Kaskade", genre: "House")
fest5.artists.create(name: "Mr Carmack", genre: "Hip Hop")
fest1.artists.create(name: "Goldlink", genre: "Trip Hop")
fest2.artists.create(name: "Adele", genre: "Pop")
fest3.artists.create(name: "Bruno Mars", genre: "Pop")
fest4.artists.create(name: "Lil Wayne", genre: "Hip Hop")
fest5.artists.create(name: "Drake", genre: "Hip Hop")
